### ISSUE TITLE
Provide a endpoint to return a plugin list which contains the gav

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkinsci/pipeline-restful-api-plugin#8]

**Comment by sladyn98** [comment]
If you need help implementing this , I could take a look :)

**Comment by LinuxSuRen** [comment]
Of course, and thanks very much. I hope the current plugin could provide this endpoint, then [jci](https://github.com/jenkins-zh/jenkins-cli) can take it to print the plugin list:
`jcli plugin list --gav -o yaml`

the output could be like this:
```
  - groupId: "org.csanchez.jenkins.plugins"
    artifactId: "kubernetes"
    source:
      version: "1.24.1"
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "kubernetes-client-api"
    source:
      version: 4.8.0-1
```

So, we can write [a custom Jenkins formula](https://github.com/jenkins-zh/docker-zh/blob/master/formulas/k8s.yaml#L17) easily.
